### ISSUE TITLE
Hangs on large file input

### ISSUE THREAD

**Issue by spacer59** [timjnh/log_app#1]
Hi Tim, thanks for the submission and appreciate the effort!

I was reviewing the submission and used a fairly large file 16MB to search for 'doesnotexist'. The app seemed unresponsive. This may be due to reading byte-byte. As you mentioned reading in chunks will improve the performance. Can you please address this issue?

Everything else looks good to me.

Again, thank you for your efforts!

**Comment by timjnh** [comment]
Hey, sorry for the delay. I wasn’t expecting feedback through GitHub. I’m really surprised it fails with 16mb input. I tested up to about a GB.  I’m wondering if I forgot to abort the loop at the start of the file? I’m unfortunately on PTO this week and don’t have access to a computer. I’ll should be able to have a look at it on Sunday when I’m back though. Apologies again for the delay

**Comment by spacer59** [comment]
No worries, it just took a really long time but in the end did return an empty result. I used `/var/log/install.log` on my m/c. Enjoy your PTO! We will wait for your response next week. Thank you for the effort!

**Comment by timjnh** [comment]
Hey Kunal, wow, you were 100% right.  I'm not sure where I went wrong during my testing.  I pushed up a couple new iterations.  There's an explanation in the readme of the process I went through in the Performance section.  Looking forward to your feedback!
